version: "{build}"

skip_tags: true
clone_folder: c:\projects\conductor
clone_depth: 5

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune

#test_script:
#  - node --version
#  - npm --version
#  - npm test

build_script:
  - node --version
  - npm --version
  - npm run dist

test: off
